accounts/urls.py
from django.conf.urls import url

from .views import AccountEmailActivateView, LoanView, cancel_loan, deduct_interest


app_name = 'Account'


urlpatterns = [
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
    url(r'^bank/loan$', LoanView.as_view(), name='loan'),
    url(r'^bank/loan/deduct$', cancel_loan, name='cancel_loan'),
    url(r'^bank/interest/deduct$', deduct_interest, name='deduct_interest'),
]

market/urls.py
from django.conf.urls import url

from .views import (
    CompanySelectionView,
    CompanyTransactionView,
    CompanyCMPChartData,
    CompanyCMPCreateView,
    CompanyAdminCompanyUpdateView,
    deduct_tax,
    update_market
)


app_name = 'Market'


urlpatterns = [
    url(r'^select/$', CompanySelectionView.as_view(), name='company_select'),
    url(r'^transact/(?P<code>\w+)$', CompanyTransactionView.as_view(), name='transaction'),
    url(r'^admin/(?P<code>\w+)$', CompanyAdminCompanyUpdateView.as_view(), name='admin'),
    url(r'^create/$', CompanyCMPCreateView.as_view(), name='create_cmp'),
    url(r'^company/api/(?P<code>\w+)$', CompanyCMPChartData.as_view(), name='cmp_api_data'),
    url(r'^tax/$', deduct_tax, name='tax'),
    url(r'^update/$', update_market, name='update')
]

stock_bridge/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from .views import HomeView, instruction_view
from accounts.views import RegisterView, LoginView, LeaderBoardView, ProfileView, NewsView
from market.views import UserTransactionHistoryView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^news/$', NewsView.as_view(), name='news'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^leaderboard/$', LeaderBoardView.as_view(), name='leaderboard'),
    url(r'^instructions/$', instruction_view, name='instructions'),
    url(r'^stocks/', include('market.urls', namespace='market')),
    url(r'^history/$', UserTransactionHistoryView.as_view(), name='transaction_history'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

<!-- FontAwesome CSS -->
<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

templates/base/footer.html
<footer class="footer-custom">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-copyright">
                <p class="text-center">
                    <a class="anchor-black" href="https://morphosis.org.in/" target="_blank">M O R P H O S I S</a>
                </p>
            </div>
            <div class="col-md-4 mx-auto">
                <h3 class="text-center"><i class="fas fa-chart-line" aria-hidden="true"></i><br>
                    Stock Bridge
                </h3>
                <p class="text-center">© 2018, Stock Bridge</p>
            </div>
            <div class="col-md-4 social-networks">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a class="anchor-black" target="_blank" href="https://www.instagram.com/nitmz_morphosis/">
                            <i class="fab fa-instagram" aria-hidden="true"></i>
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                    <li class="list-inline-item">
                        <a class="anchor-black" target="_blank" href="https://www.facebook.com/NITMz.morphosis/">
                            <i class="fab fa-facebook-f" aria-hidden="true"></i>
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                    <li class="list-inline-item">
                        <a class="anchor-black" target="_blank" href="https://www.linkedin.com/company/13677719/">
                            <i class="fab fa-linkedin-in" aria-hidden="true"></i>
                        </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                    <li class="list-inline-item">
                        <a class="anchor-black" target="_blank" href="https://github.com/morphosis-nitmz">
                            <i class="fab fa-github" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/base/js.html
{% load static %}

<!-- jQuery JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Tether JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

<!-- jQuery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<!-- Chart.js CDN-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

templates/base/navbar.html
{% load humanize %}
{% url 'home' as home_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'logout' as logout_url %}
{% url 'transaction_history' as transaction_history_url %}
{% url 'leaderboard' as leaderboard_url %}
{% url 'news' as news_url %}
{% url 'account:loan' as loan_url %}
{% url 'instructions' as instructions_url %}
{% url 'profile' request.user.username as profile_url %}
{% url 'market:company_select' as market_url %}

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
	<div class="container">
		<a class="navbar-brand" href="{{ home_url }}">
			<i class="fas fa-chart-line" aria-hidden="true"></i>
			{% if brand_name %} {{ brand_name}} {% else %} Stock Bridge {% endif %}
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item {% if request.path == home_url %}active{% endif %}">
					<a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
				</li>
				{% if request.user.is_authenticated %}
					<li class="nav-item {% if request.path == market_url %}active{% endif %}">
						<a class="nav-link" href="{{ market_url }}">Market</a>
					</li>
					<li class="nav-item {% if request.path == loan_url %}active{% endif %}">
						<a class="nav-link" href="{{ loan_url }}">Bank</a>
					</li>
					<li class="nav-item {% if request.path == news_url %}active{% endif %}">
						<a class="nav-link" href="{{ news_url }}">News (<small>{{ request.session.news }}</small>)</a>
					</li>
				{% endif %}
				<li class="nav-item {% if request.path == leaderboard_url %}active{% endif %}">
					<a class="nav-link" href="{{ leaderboard_url }}">Leaderboard</a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if request.user.is_authenticated %}
					<li class="nav-item mr-4">
						<a class="nav-link disabled" style="color: white" href="#">Cash: &#8377; {{ request.user.cash|intcomma }}</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Account
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">Profile</a>
							<a class="dropdown-item {% if request.path == transaction_history_url %}active{% endif %}" href="{{ transaction_history_url }}">History</a>
							<a class="dropdown-item {% if request.path == instructions_url %}active{% endif %}" href="{{ instructions_url }}">Instructions</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item {% if request.path == logout_url %}active{% endif %}" href="{{ logout_url }}">Logout</a>
						</div>
					</li>
					{% if request.user.is_superuser %}
						<li class="nav-item">
							<a class="nav-link" href="/admin/" target="blank">Admin</a>
						</li>
					{% endif %}
				{% else %}
					<li class="nav-item {% if request.path == login_url %}active{% endif %}">
						<a class="nav-link" href="{{ login_url }}">Login</a>
					</li>
					<li class="nav-item {% if request.path == register_url %}active{% endif %}">
						<a class="nav-link" href="{{ register_url }}">Register</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>