accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'
        ),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
        ),
    url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'
        ),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
        ),
    url(r'^password/reset/\
            (?P<uidb64>[0-9A-Za-z_\-]+)/\
            (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
        ),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
        ),
]

accounts/urls.py
from django.conf.urls import url

from .views import AccountEmailActivateView, LoanView, cancel_loan, deduct_interest


app_name = 'Account'


urlpatterns = [
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
    url(r'^bank/loan$', LoanView.as_view(), name='loan'),
    url(r'^bank/loan/deduct$', cancel_loan, name='cancel_loan'),
    url(r'^bank/interest/deduct$', deduct_interest, name='deduct_interest'),
]

market/urls.py
from django.conf.urls import url

from .views import (
    CompanySelectionView,
    CompanyTransactionView,
    CompanyCMPChartData,
    CompanyCMPCreateView,
    CompanyAdminCompanyUpdateView,
    deduct_tax,
    update_market
)


app_name = 'Market'


urlpatterns = [
    url(r'^select/$', CompanySelectionView.as_view(), name='company_select'),
    url(r'^transact/(?P<code>\w+)$', CompanyTransactionView.as_view(), name='transaction'),
    url(r'^admin/(?P<code>\w+)$', CompanyAdminCompanyUpdateView.as_view(), name='admin'),
    url(r'^create/$', CompanyCMPCreateView.as_view(), name='create_cmp'),
    url(r'^company/api/(?P<code>\w+)$', CompanyCMPChartData.as_view(), name='cmp_api_data'),
    url(r'^tax/$', deduct_tax, name='tax'),
    url(r'^update/$', update_market, name='update')
]

stock_bridge/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from .views import HomeView, instruction_view
from accounts.views import RegisterView, LoginView, LeaderBoardView, ProfileView, NewsView
from market.views import UserTransactionHistoryView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^news/$', NewsView.as_view(), name='news'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^leaderboard/$', LeaderBoardView.as_view(), name='leaderboard'),
    url(r'^instructions/$', instruction_view, name='instructions'),
    url(r'^stocks/', include('market.urls', namespace='market')),
    url(r'^history/$', UserTransactionHistoryView.as_view(), name='transaction_history'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, FormView, CreateView, View
from django.views.generic.edit import FormMixin
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.urls import reverse

from .forms import LoginForm, RegisterForm, ReactivateEmailForm
from .models import EmailActivation, News
from stock_bridge.mixins import (
    AnonymousRequiredMixin,
    RequestFormAttachMixin,
    NextUrlMixin,
    LoginRequiredMixin,
    CountNewsMixin
)
from market.models import InvestmentRecord


User = get_user_model()

START_TIME = timezone.make_aware(getattr(settings, 'START_TIME'))
STOP_TIME = timezone.make_aware(getattr(settings, 'STOP_TIME'))


@login_required
def cancel_loan(request):
    """ Deduct entire loan amount from user's balance """
    if request.user.is_superuser:
        for user in User.objects.all():
            user.cancel_loan()
        return HttpResponse('Loan Deducted', status=200)
    return redirect('home')


@login_required
def deduct_interest(request):
    """ Deduct interest from user's balance """
    if request.user.is_superuser:
        for user in User.objects.all():
            user.deduct_interest()
        return HttpResponse('Interest Deducted', status=200)
    return redirect('home')


class NewsView(LoginRequiredMixin, CountNewsMixin, ListView):
    template_name = 'accounts/news.html'
    queryset = News.objects.filter(is_active=True)


class LoanView(LoginRequiredMixin, CountNewsMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'accounts/loan.html', {
            'user': request.user
        })

    def post(self, request, *args, **kwargs):
        current_time = timezone.make_aware(datetime.now())
        if current_time >= START_TIME and current_time <= STOP_TIME:  # transaction has to be within game time
            mode = request.POST.get('mode')
            user = request.user
            if mode == 'issue':
                if user.issue_loan():
                    messages.success(request, 'Loan has been issued.')
                else:
                    messages.error(request, 'You can issue loan only 1 time!')
            elif mode == 'pay':
                if user.pay_installment():
                    messages.success(request, 'Installment paid!')
                else:
                    messages.error(
                        request,
                        'Minimum installment amount has to be INR 5,000 and you should have sufficient balance.'
                    )
        else:
            # msg = 'The market will be live from {start} to {stop}'.format(
            #     start=START_TIME.strftime('%H:%M'),
            #     stop=STOP_TIME.strftime('%H:%M')
            # )
            msg = 'The market is closed!'
            messages.info(request, msg)
        return redirect('account:loan')


class ProfileView(LoginRequiredMixin, CountNewsMixin, DetailView):
    template_name = 'accounts/profile.html'

    def dispatch(self, request, *args, **kwargs):
        # only the user himself can view his own profile
        if request.user.username != kwargs.get('username'):
            return redirect('/')
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        username = self.kwargs.get('username')
        instance = User.objects.filter(username=username).first()
        if instance is None:
            raise Http404('User not found')
        return instance

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        qs = InvestmentRecord.objects.filter(user=self.request.user)
        if qs.count() >= 1:
            context['net_worth'] = InvestmentRecord.objects.calculate_net_worth(self.request.user)
            context['investments'] = qs
        return context


class LeaderBoardView(CountNewsMixin, View):
    template_name = 'accounts/leaderboard.html'

    def get(self, request, *args, **kwargs):
        data = []
        user_qs = User.objects.all()
        for user in user_qs:
            net_worth = InvestmentRecord.objects.calculate_net_worth(user)
            data.append((user.username, user.full_name, net_worth, user.coeff_of_variation))
        data = sorted(data, key=lambda d: (-d[2], d[3]))
        return render(request, 'accounts/leaderboard.html', {'data': data})


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None

    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:  # Not confirmed but confirmable
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, 'Your email has been confirmed! Please login to continue.')
                return redirect('login')
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse('password_reset')
                    msg = """Your email has already been confirmed.
                    Do you want to <a href="{link}">reset you password</a>?""".format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect('login')
        context = {'form': self.get_form(), 'key': key}  # get_form() works because of the mixin
        return render(request, 'registration/activation_error.html', context)

    def post(self, request, *args, **kwargs):
        # create a form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = 'Activation link sent. Please check your email.'
        messages.success(self.request, msg)
        email = form.cleaned_data.get('email')
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        """
        This method had to be explicitly written because this view uses the basic django "View" class.
        If it had used some other view like ListView etc. Django would have handled it automatically.
        """
        context = {'form': form, 'key': self.key}
        return render(self.request, 'registration/activation_error.html', context)


class LoginView(AnonymousRequiredMixin, RequestFormAttachMixin, NextUrlMixin, FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/'
    default_url = '/'
    default_next = '/'

    def form_valid(self, form):
        request = self.request
        response = form.cleaned_data
        if not response.get('success'):
            messages.warning(request, mark_safe(response.get('message')))
            return redirect('login')
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(AnonymousRequiredMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'

    def form_valid(self, form):
        super(RegisterView, self).form_valid(form)
        messages.success(self.request, 'Verification link sent! Please check your email.')
        return redirect(self.success_url)

accounts/templates/accounts/leaderboard.html
{% extends 'base.html' %}

{% block base_head %}
<title>Leaderboard</title>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12 my-3">
		<h1 class="heading">LeaderBoard</h1>
	</div>
</div>
<div class="row">
    <div class="col-12 my-3">
        <div class="alert alert-danger text-center" role="alert">
          Please check the news section frequently.
        </div>
    </div>
</div>
<div class="jumbotron" style="padding-top: 15px;padding-left: 10px ;padding-bottom: 5px;margin-bottom:10px;margin-top:8px; ">
    <div class="row">
        <div class="col-12 my-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Rank</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Net Worth</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in data %}
                        {% if object.0 == request.user.username %}
                            <tr style="background-color:rgb(224, 129, 129)">
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center">
                                    <a href="{% url 'profile' object.0 %}">
                                        {{ object.1 }}
                                    </a>
                                </td>
                                <td class="text-center">&#8377; {{ object.2 }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center">{{ object.1 }}</td>
                                <td class="text-center">&#8377; {{ object.2 }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/loan.html
{% extends 'base.html' %}

{% block base_head %}
<title>Bank</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12 mt-3 mb-5">
        <h1 class="heading">World Bank</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-6 text-center">
        <h3>Credit Loan</h3>
        <p class="lead">Amount: &#8377; 5,000</p>
        <form method="POST" action="{% url 'account:loan' %}"> {% csrf_token %}
            <input type="hidden" name="mode" value="issue">
            <button type="submit" class="btn btn-success">Issue</button>
        </form>
    </div>
    <div class="col-12 col-md-6 text-center">
        <h3>Loan Due</h3>
        <p class="lead">Amount Due: &#8377; {{ user.loan }}<br>
            Balance Available: &#8377; {{ user.cash }}<br>
            Pay an installment of &#8377; 5,000</p>
        <form method="POST" action="{% url 'account:loan' %}"> {% csrf_token %}
            <input type="hidden" name="mode" value="pay">
            <button type="submit" class="btn btn-success">Repay</button>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block base_head %}
<title>Login</title>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<h1 class="text-center">Login</h1>
	</div>
</div>
<hr/>
<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<form method="POST"> {% csrf_token %}
		{{ form }}
		<div class="row">
			<div class="col my-1 mr-auto">
				<button type="submit" class="btn btn-primary">Sign In</button>
			</div>
			<div class="col my-3 ml-auto">
				<a href="{% url 'password_reset' %}" target="blank">Forgot Password?</a>
			</div>
		</div>
		</form>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/news.html
{% extends 'base.html' %}

{% block base_head %}
<title>News</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12 text-center my-3">
        <h1 class="heading">News</h1>
    </div>
</div>
{% if object_list %}
<div class="row">
    {% for object in object_list %}
        <div class="col-12">
            <div class="alert alert-success text-center" role="alert">
              {{ object.content|linebreaks }}
            </div>
        </div>
    {% endfor %}
</div>
{% else %}
<div class="row">
    <div class="col-12 text-center mt-5 pt-5">
        <h3 class="lead">No news available</h3>
    </div>
</div>
{% endif %}

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load humanize %}

{% block base_head %}
<title>Profile</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12 mt-3">
        <div class="text-center">
            <h1 class="heading">{{ object.full_name }}</h1>
            <p class="lead">{{ object.username }}</p>
            <p class="lead">{{ object.email }}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 text-center my-5">
        <h3>Net Worth: &#8377; {{ net_worth|intcomma }}</h3>
    </div>
</div>
{% if investments %}
    <div class="row">
        <div class="col-12">
            <h3>Investment Record:</h3>
        </div>
        <div class="col-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">S.no</th>
                        <th class="text-center">Company</th>
                        <th class="text-center">Stocks Purchased</th>
                        <th class="text-center">Stocks Available</th>
                        <th class="text-center">Current Market Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for investment in investments %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td class="text-center">
                                <a href="{% url 'market:transaction' investment.company.code %}">
                                    {{ investment.company }}
                                </a>
                            </td>
                            <td class="text-center">{{ investment.stocks }}</td>
                            <td class="text-center">{{ investment.company.stocks_remaining }}</td>
                            <td class="text-center">
                                &#8377; {{ investment.company.cmp }}
                                {% if investment.company.change >= 0 %}
                                    <small style="color: green">
                                        ({{ investment.company.change }}%) <i class="fa fa-arrow-up"></i>
                                    </small><br>
                                {% elif investment.company.change < 0 %}
                                    <small style="color: red">
                                        ({{ investment.company.change }}%) <i class="fa fa-arrow-down"></i>
                                    </small><br>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block base_head %}
<title>Register</title>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<h1 class="text-center">Register</h1>
	</div>
</div>
<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<form method="POST"> {% csrf_token %}
	    {{ form }}
	    <button type="submit" class="btn btn-primary">Sign Up</button>
		</form>
	</div>
</div>

{% endblock %}