market/urls.py
from django.conf.urls import url

from .views import (
    CompanySelectionView,
    CompanyTransactionView,
    CompanyCMPChartData,
    CompanyCMPCreateView,
    CompanyAdminCompanyUpdateView,
    deduct_tax,
    update_market
)


app_name = 'Market'


urlpatterns = [
    url(r'^select/$', CompanySelectionView.as_view(), name='company_select'),
    url(r'^transact/(?P<code>\w+)$', CompanyTransactionView.as_view(), name='transaction'),
    url(r'^admin/(?P<code>\w+)$', CompanyAdminCompanyUpdateView.as_view(), name='admin'),
    url(r'^create/$', CompanyCMPCreateView.as_view(), name='create_cmp'),
    url(r'^company/api/(?P<code>\w+)$', CompanyCMPChartData.as_view(), name='cmp_api_data'),
    url(r'^tax/$', deduct_tax, name='tax'),
    url(r'^update/$', update_market, name='update')
]

stock_bridge/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from .views import HomeView, instruction_view
from accounts.views import RegisterView, LoginView, LeaderBoardView, ProfileView, NewsView
from market.views import UserTransactionHistoryView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^news/$', NewsView.as_view(), name='news'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^leaderboard/$', LeaderBoardView.as_view(), name='leaderboard'),
    url(r'^instructions/$', instruction_view, name='instructions'),
    url(r'^stocks/', include('market.urls', namespace='market')),
    url(r'^history/$', UserTransactionHistoryView.as_view(), name='transaction_history'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/forms.py
from django import forms

from .models import TRANSACTION_MODES


class StockTransactionForm(forms.Form):
    """ Form for users to make stocks transaction """
    mode = forms.ChoiceField(choices=TRANSACTION_MODES)
    quantity = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'pattern': '[0-9]+',
        'title': 'Enter integers only',
        'placeholder': 'Enter integers only'
    }))


class CompanyChangeForm(forms.Form):
    """ Form for admin to change company's CMP """
    price = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'pattern': '[0-9]+',
        'title': 'Enter integers only',
        'placeholder': 'Enter integers only'
    }))

market/views.py
from datetime import datetime
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View, ListView
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.utils.timezone import localtime

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Company, CompanyCMPRecord, InvestmentRecord, Transaction
from .forms import StockTransactionForm, CompanyChangeForm
from stock_bridge.mixins import LoginRequiredMixin, CountNewsMixin, AdminRequiredMixin


User = get_user_model()
START_TIME = timezone.make_aware(getattr(settings, 'START_TIME'))
STOP_TIME = timezone.make_aware(getattr(settings, 'STOP_TIME'))


@login_required
def deduct_tax(request):
    """ Deduct income tax """
    if request.user.is_superuser:
        for user in User.objects.all():
            tax = user.cash * Decimal(0.4)
            user.cash -= tax
            user.save()
        return HttpResponse('success')
    return redirect('/')


@login_required
def update_market(request):
    """ Update company's cmp after applying formula """
    if request.user.is_superuser:
        # update company cmp data
        company_qs = Company.objects.all()
        for company in company_qs:
            company.update_cmp()
            obj = CompanyCMPRecord.objects.create(company=company, cmp=company.cmp)
        return HttpResponse('cmp updated')
    return redirect('/')


class CompanyAdminCompanyUpdateView(AdminRequiredMixin, View):
    """ View for admin to change company's CMP """

    def get(self, request, *args, **kwargs):
        company = Company.objects.get(code=kwargs.get('code'))
        return render(request, 'market/admin_company_change.html', {
            'object': company,
            'company_list': Company.objects.all(),
            'form': CompanyChangeForm()
        })

    def post(self, request, *args, **kwargs):
        company = Company.objects.get(code=kwargs.get('code'))
        price = request.POST.get('price')
        old_price = company.cmp
        company.cmp = Decimal(int(price))
        company.save()
        company.calculate_change(old_price)
        print('price', int(price))
        url = reverse('market:admin', kwargs={'code': company.code})
        return HttpResponseRedirect(url)


class CompanyCMPCreateView(View):

    def get(self, request, *args, **kwargs):
        for company in Company.objects.all():
            obj = CompanyCMPRecord.objects.create(company=company, cmp=company.cmp)
        return HttpResponse('success')


class CompanySelectionView(LoginRequiredMixin, CountNewsMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'market/select_company.html', {
            'object_list': Company.objects.all()
        })


class CompanyCMPChartData(APIView):  # used django rest framework
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None, *args, **kwargs):
        qs = CompanyCMPRecord.objects.filter(company__code=kwargs.get('code'))
        if qs.count() > 15:
            qs = qs[:15]
        qs = reversed(qs)  # reverse timestamp sorting i.e. latest data should be in front
        labels = []
        cmp_data = []
        for cmp_record in qs:
            labels.append(localtime(cmp_record.timestamp).strftime('%H:%M'))
            cmp_data.append(cmp_record.cmp)
        current_cmp = Company.objects.get(code=kwargs.get('code')).cmp
        if cmp_data[-1] != current_cmp:
            labels.append(timezone.make_aware(datetime.now()).strftime('%H:%M'))
            cmp_data.append(current_cmp)
        data = {
            "labels": labels,
            "cmp_data": cmp_data,
        }
        return Response(data)


class CompanyTransactionView(LoginRequiredMixin, CountNewsMixin, View):

    def get(self, request, *args, **kwargs):
        company = Company.objects.get(code=kwargs.get('code'))
        obj, created = InvestmentRecord.objects.get_or_create(user=request.user, company=company)
        stocks_owned = obj.stocks
        return render(request, 'market/transaction_market.html', {
            'object': company,
            'company_list': Company.objects.all(),
            'stocks_owned': stocks_owned,
            'form': StockTransactionForm()
        })

    def post(self, request, *args, **kwargs):
        company = Company.objects.get(code=kwargs.get('code'))
        current_time = timezone.make_aware(datetime.now())
        if current_time >= START_TIME and current_time <= STOP_TIME:
            user = request.user
            mode = request.POST.get('mode')
            quantity = int(request.POST.get('quantity'))
            price = company.cmp
            investment_obj, obj_created = InvestmentRecord.objects.get_or_create(user=user, company=company)
            if quantity > 0:
                if mode == 'buy':
                    purchase_amount = Decimal(quantity) * price
                    if user.cash >= purchase_amount:
                        if company.stocks_remaining >= quantity:
                            # user.buy_stocks(quantity, price)
                            # company.user_buy_stocks(quantity)
                            # investment_obj.add_stocks(quantity)
                            obj = Transaction.objects.create(
                                user=user,
                                company=company,
                                num_stocks=quantity,
                                price=price,
                                mode=mode,
                                user_net_worth=InvestmentRecord.objects.calculate_net_worth(user)
                            )
                            messages.success(request, 'Transaction Complete!')
                        else:
                            messages.error(request, 'The company does not have that many stocks left!')
                    else:
                        messages.error(request, 'Insufficient Balance for this transaction!')
                elif mode == 'sell':
                    if quantity <= investment_obj.stocks and quantity <= company.stocks_offered:
                        # user.sell_stocks(quantity, price)
                        # company.user_sell_stocks(quantity)
                        # investment_obj.reduce_stocks(quantity)
                        obj = Transaction.objects.create(
                            user=user,
                            company=company,
                            num_stocks=quantity,
                            price=price,
                            mode=mode,
                            user_net_worth=InvestmentRecord.objects.calculate_net_worth(user)
                        )
                        messages.success(request, 'Transaction Complete!')
                    else:
                        messages.error(request, 'Please enter a valid quantity!')
                else:
                    messages.error(request, 'Please enter a valid mode!')
            else:
                messages.error(request, 'The quantity cannot be negative!')
        else:
            # msg = 'The market will be live from {start} to {stop}'.format(
            #     start=START_TIME.strftime('%H:%M'),
            #     stop=STOP_TIME.strftime('%H:%M')
            # )
            msg = 'The market is closed!'
            messages.info(request, msg)
        url = reverse('market:transaction', kwargs={'code': company.code})
        return HttpResponseRedirect(url)


class UserTransactionHistoryView(LoginRequiredMixin, CountNewsMixin, ListView):
    template_name = 'market/user_transaction_history.html'

    def get_queryset(self, *args, **kwargs):
        return Transaction.objects.get_by_user(user=self.request.user)

market/templates/market/admin_company_change.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block base_head %}
<title>Admin Market</title>
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light mt-3 mb-4" style="background-color: #dcdce1; font-color: #000000;">
  <a class="navbar-brand" href="#">Companies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        {% for company in company_list %}
            {% if company == object %}
                <li class="nav-item active">
                    <a class="nav-link anchor-black" href="{{ company.get_absolute_admin_url }}">{{ company.name }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link anchor-black" href="{{ company.get_absolute_admin_url }}">{{ company.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
      </ul>
  </div>
</nav>

<div class="row">
    <div class="col mx-auto my-3">
        <div class="text-center">
            <h1 class="heading">{{ object.name }}</h1>
            <p>
                <strong>Industry:</strong> {{ object.industry }}<br>
                <strong>Cap Type:</strong> {{ object.get_cap }}<br>
                <strong>Cap Size:</strong> &#8377; {{ object.cap|intcomma }}
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-4 my-5 mx-auto text-center">
        <h3>{{ object.code }}</h3>
        Total Stocks: {{ object.stocks_offered }}<br>
        Stocks Remaining: {{ object.stocks_remaining }}<br>
        Current Price per stock: &#8377; {{ object.cmp }}
        {% if object.change >= 0 %}
            <small style="color: green">({{ object.change }}%) <i class="fa fa-arrow-up"></i></small><br>
        {% elif object.change < 0 %}
            <small style="color: red">({{ object.change }}%) <i class="fa fa-arrow-down"></i></small><br>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-6 text-center mx-auto mt-5">
        <form method="POST" action="{% url 'market:admin' object.code %}"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Change</button>
        </form>
    </div>
</div>

{% endblock %}

market/templates/market/select_company.html
{% extends 'base.html' %}
{% block base_head %}
<title>Select</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col mt-3 mb-5">
        <h1 class="heading">Market</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 mx-auto text-center mt-5">
        <div class="dropdown show">
            <button class="btn btn-info btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Choose Company
            </button>
            <div class="dropdown-menu">
                {% for object in object_list %}
                    <a class="dropdown-item" href="{{ object.get_absolute_url }}">{{ object.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

market/templates/market/transaction_market.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block base_head %}
<title>Transaction</title>
{% endblock %}

{% block javascript %}

<script>
$(document).ready(function(){
    var endpoint = '{% url "market:cmp_api_data" object.code %}'
    var defaultData = []
    var labels = [];
    $.ajax({
        method: "GET",
        url: endpoint,
        success: function (data) {
            labels = data.labels
            defaultData = data.cmp_data
            setChart()
        },
        error: function (error_data) {
            console.log("error")
            console.log(error_data)
        }
    })

    function setChart() {
        var ctx = document.getElementById("cmpChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Current Market Price',
                    data: defaultData,
                    backgroundColor: 'rgba(122, 242, 14, 0.2)',
                    borderColor: 'rgba(10, 12, 12, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    }
})
</script>

{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light mt-3 mb-4" style="background-color: #dcdce1; font-color: #000000;">
  <a class="navbar-brand" href="#">Companies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        {% for company in company_list %}
            {% if company == object %}
                <li class="nav-item active">
                    <a class="nav-link anchor-black" href="{{ company.get_absolute_url }}">{{ company.name }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link anchor-black" href="{{ company.get_absolute_url }}">{{ company.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
      </ul>
  </div>
</nav>

<div class="row">
    <div class="col mx-auto my-3">
        <div class="text-center">
            <h1 class="heading">{{ object.name }}</h1>
            <p>
                <strong>Industry:</strong> {{ object.industry }}<br>
                <strong>Cap Type:</strong> {{ object.get_cap }}<br>
                <strong>Cap Size:</strong> &#8377; {{ object.cap|intcomma }}
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-8 my-5 mr-auto">
        <canvas id="cmpChart" width="400" height="200"></canvas>
    </div>
    <div class="col-12 col-md-4 my-5 ml-auto text-center">
        <h3>{{ object.code }}</h3>
        Total Stocks: {{ object.stocks_offered }}<br>
        Stocks Remaining: {{ object.stocks_remaining }}<br>
        Current Price per stock: &#8377; {{ object.cmp }}
        {% if object.change >= 0 %}
            <small style="color: green">({{ object.change }}%) <i class="fa fa-arrow-up"></i></small><br>
        {% elif object.change < 0 %}
            <small style="color: red">({{ object.change }}%) <i class="fa fa-arrow-down"></i></small><br>
        {% endif %}
        Stocks Currently Owned: {{ stocks_owned }}
    </div>
</div>
<div class="row">
    <div class="col-6 text-center mx-auto mt-5">
        <p style="font-size: 25px;"><b>Balance Available:</b> &#8377; {{ request.user.cash }}</p><br>
        <form method="POST" action="{% url 'market:transaction' object.code %}"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Transact</button>
        </form>
    </div>
</div>

{% endblock %}

market/templates/market/user_transaction_history.html
{% extends 'base.html' %}

{% block base_head %}
<title>Transaction History</title>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12 my-3">
		<h1 class="heading">Transaction History</h1>
	</div>
</div>
<div class="jumbotron" style="padding-top: 15px;padding-left: 10px ;padding-bottom: 5px;margin-bottom:10px;margin-top:8px; ">
    <div class="row">
        <div class="col-12 my-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center">S. No.</th>
                        <th class="text-center">Company</th>
                        <th class="text-center">Mode</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td class="text-center">{{ object.company }}</td>
                            <td class="text-center">{{ object.mode }}</td>
                            <td class="text-center">&#8377; {{ object.price }}</td>
                            <td class="text-center">{{ object.num_stocks }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}